"""Level 1 deterministic historical-context alert engine.

Alerts are generated by comparing the active well's current drilling depth
against the depths of historical events recorded in reference (offset) wells.
They provide historical evidence and context only — never predictions or
operational commands.

Advisory-language constraints (non-negotiable):
  USE:    'recorded precedent', 'historical context', 'was recorded at',
          'was observed at', 'recorded as precedent'
  NEVER:  'will happen', 'will', 'predicted', 'expect', 'must', 'you should'

Public API
----------
HistoricalEvent          -- a past drilling event from a reference well
AlertResult              -- a generated historical-context alert
compute_risk_score(...)  -- risk score in [0, 1] based on depth proximity
check_proximity_alerts(current_depth, reference_events, window_m)
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Optional


# ── Data types ────────────────────────────────────────────────────────────────

@dataclass
class HistoricalEvent:
    """A past drilling event from a reference well, loaded from the NWIS database."""

    event_id: str
    event_type: str           # MUD_LOSS | HELD_UP | TIGHT_PULL | CASING_FAILURE | …
    depth_md: float           # Always measured depth — never silently converted.
    well_id: str
    severity: Optional[str] = None    # LOW | MEDIUM | HIGH | CRITICAL
    volume_bbl: Optional[float] = None


@dataclass
class AlertResult:
    """A historical-context alert for the active drilling well."""

    alert_id: str
    level: str                # INFO | WARNING | CRITICAL
    category: str
    trigger_depth_md: float
    advisory_text: str        # MUST use 'recorded precedent' language
    risk_score: float         # In [0, 1]
    source_event_id: str


# ── Risk scoring ──────────────────────────────────────────────────────────────

_SEVERITY_WEIGHTS: dict[str, float] = {
    "LOW": 0.20,
    "MEDIUM": 0.50,
    "HIGH": 0.80,
    "CRITICAL": 1.00,
}
_DEFAULT_SEVERITY_WEIGHT = 0.20
_PROXIMITY_DECAY_M = 20.0  # e-folding scale for exponential proximity decay (metres)


def compute_risk_score(
    events: list[HistoricalEvent],
    current_depth: float,
    proximity_window_m: float = 50.0,
) -> float:
    """Return a risk score in [0, 1] for events near *current_depth*.

    Score is the sum of severity-weighted, exponentially-decayed proximity
    terms over all events within *proximity_window_m*, capped at 1.0.

    An event exactly at *current_depth* with CRITICAL severity contributes
    a term of 1.0 × exp(0) = 1.0; distance increases reduce the contribution.
    """
    total = 0.0
    for ev in events:
        dist = abs(ev.depth_md - current_depth)
        if dist <= proximity_window_m:
            weight = _SEVERITY_WEIGHTS.get(ev.severity or "", _DEFAULT_SEVERITY_WEIGHT)
            decay = math.exp(-dist / _PROXIMITY_DECAY_M)
            total += weight * decay
    return min(round(total, 4), 1.0)


# ── Alert level classification ────────────────────────────────────────────────

def _classify_level(risk_score: float, severity: Optional[str]) -> str:
    if severity == "CRITICAL" or risk_score >= 0.75:
        return "CRITICAL"
    if severity in ("HIGH", "MEDIUM") or risk_score >= 0.40:
        return "WARNING"
    return "INFO"


# ── Advisory text templates ───────────────────────────────────────────────────

_ADVISORY_TEMPLATES: dict[str, str] = {
    "MUD_LOSS": (
        "Historical context: mud loss was recorded at this depth interval in a reference well"
    ),
    "HELD_UP": (
        "Historical context: a pipe held-up condition was recorded at this depth interval"
    ),
    "TIGHT_PULL": (
        "Historical context: tight-pull overpull was observed at this depth interval "
        "during a reference well trip"
    ),
    "CASING_FAILURE": (
        "Historical context: casing failure has been recorded as precedent in this depth zone"
    ),
    "KICK": (
        "Historical context: a well-control kick event was recorded at this depth interval"
    ),
}
_DEFAULT_ADVISORY = (
    "Historical context: a drilling hazard was recorded as precedent in this depth zone"
)


def _build_advisory(event: HistoricalEvent, current_depth: float) -> str:
    """Return an advisory text string constrained to historical-context language."""
    base = _ADVISORY_TEMPLATES.get(event.event_type.upper(), _DEFAULT_ADVISORY)
    dist = abs(event.depth_md - current_depth)
    reference = (
        f"This recorded precedent is from well {event.well_id} "
        f"at {event.depth_md:.0f} m MD"
        + (f", {dist:.0f} m from the current depth" if dist > 0 else " (at current depth)")
        + "."
    )
    return f"{base}. {reference}"


# ── Public API ────────────────────────────────────────────────────────────────

def check_proximity_alerts(
    current_depth: float,
    reference_events: list[HistoricalEvent],
    proximity_window_m: float = 50.0,
) -> list[AlertResult]:
    """Return alerts for all reference events within *proximity_window_m* of *current_depth*.

    Each alert carries historical-context advisory text only.  No operational
    commands, predictions, or certainty statements are generated.

    Parameters
    ----------
    current_depth:      Active well's current depth (measured depth, metres).
    reference_events:   Historical events from offset / reference wells.
    proximity_window_m: Depth window in metres; events outside this range are ignored.

    Returns
    -------
    List of AlertResult, one per triggered event, ordered as events were supplied.
    """
    results: list[AlertResult] = []
    for idx, ev in enumerate(reference_events):
        dist = abs(ev.depth_md - current_depth)
        if dist > proximity_window_m:
            continue

        risk = compute_risk_score([ev], current_depth, proximity_window_m)
        level = _classify_level(risk, ev.severity)
        advisory = _build_advisory(ev, current_depth)

        results.append(
            AlertResult(
                alert_id=f"ALERT-{ev.event_id}-{idx:03d}",
                level=level,
                category=ev.event_type,
                trigger_depth_md=current_depth,
                advisory_text=advisory,
                risk_score=risk,
                source_event_id=ev.event_id,
            )
        )
    return results


# ── Database-backed API for FastAPI routers ───────────────────────────────────
#
# These async functions depend on SQLAlchemy AsyncSession and bridge the pure
# alert-engine above with the PostgreSQL persistence layer.


async def get_active_context_alerts(
    db: "AsyncSession",
    well_id: str,
    bit_md: float,
    proximity_window_m: float = 50.0,
) -> list[dict]:
    """Evaluate historical-context alerts for the active well at bit_md.

    1. Looks up similar offset wells from similarity_record.
    2. Loads their historical events near bit_md.
    3. Runs the deterministic alert engine.
    4. Returns AlertResult dicts (not persisted) for the router to serialise.
    """
    from sqlalchemy import select
    from app.models.event import Event
    from app.models.knowledge import SimilarityRecord

    # Get top similar wells.
    sim_stmt = (
        select(SimilarityRecord.candidate_well_id)
        .where(SimilarityRecord.active_well_id == well_id)
        .order_by(SimilarityRecord.composite_score.desc())
        .limit(5)
    )
    sim_result = await db.execute(sim_stmt)
    candidate_ids = [row[0] for row in sim_result.all()]

    if not candidate_ids:
        return []

    top = bit_md - proximity_window_m
    bot = bit_md + proximity_window_m

    events_stmt = (
        select(Event)
        .where(Event.well_id.in_(candidate_ids))
        .where(Event.depth_md >= top)
        .where(Event.depth_md <= bot)
        .order_by(Event.depth_md)
    )
    ev_result = await db.execute(events_stmt)
    db_events = list(ev_result.scalars().all())

    ref_events = [
        HistoricalEvent(
            event_id=ev.event_id,
            event_type=ev.event_type,
            depth_md=float(ev.depth_md),
            well_id=ev.well_id,
            severity=ev.severity,
            volume_bbl=float(ev.volume_bbl) if ev.volume_bbl is not None else None,
        )
        for ev in db_events
    ]

    alert_results = check_proximity_alerts(bit_md, ref_events, proximity_window_m)
    return [
        {
            "alert_id": 0,  # ephemeral
            "well_id": well_id,
            "level": ar.level,
            "category": ar.category,
            "trigger_depth_md": ar.trigger_depth_md,
            "advisory_text": ar.advisory_text,
            "risk_score": ar.risk_score,
            "source_event_id": ar.source_event_id,
            "is_active": True,
            "created_at": __import__("datetime").datetime.now(
                tz=__import__("datetime").timezone.utc
            ),
        }
        for ar in alert_results
    ]


async def get_alerts_from_db(
    db: "AsyncSession",
    *,
    active_well_id: str | None = None,
    is_active: bool | None = None,
) -> list:
    """Return stored Alert rows filtered by well and/or active status."""
    from sqlalchemy import select
    from app.models.alert import Alert

    stmt = select(Alert)
    if active_well_id:
        stmt = stmt.where(Alert.well_id == active_well_id)
    if is_active is not None:
        stmt = stmt.where(Alert.is_active.is_(is_active))
    stmt = stmt.order_by(Alert.created_at.desc())
    result = await db.execute(stmt)
    return list(result.scalars().all())


async def dismiss_alert_in_db(
    db: "AsyncSession",
    alert_id: int,
    *,
    reason: str | None = None,
    dismissed_by: str | None = None,
) -> object | None:
    """Set is_active=False on the given alert.  Returns the updated Alert or None."""
    from sqlalchemy import select
    from app.models.alert import Alert

    stmt = select(Alert).where(Alert.alert_id == alert_id)
    result = await db.execute(stmt)
    alert = result.scalar_one_or_none()
    if alert is None:
        return None
    alert.is_active = False
    if reason:
        alert.advisory_text = alert.advisory_text + f"\n[Dismissed by {dismissed_by}: {reason}]"
    await db.flush()
    return alert
